Repository Project-MONAI/MONAILabel, pull requests merged in 2021-09, with the labels that each got.

#320 Fix readme
  README.md
Labels: 0.2.0

#322 Add warning for nvidia-smi command
  monailabel/utils/others/planner.py
Labels: 0.2.0

#301 Add App with TTA
  monailabel/utils/scoring/test_time_augmentation.py
  monailabel/utils/scoring/tta_scoring.py
  sample-apps/segmentation_spleen/main.py
  sample-apps/segmentation_spleen_tta/README.md
  sample-apps/segmentation_spleen_tta/__init__.py
  sample-apps/segmentation_spleen_tta/lib/__init__.py
  sample-apps/segmentation_spleen_tta/lib/activelearning.py
  sample-apps/segmentation_spleen_tta/lib/infer.py
  sample-apps/segmentation_spleen_tta/lib/train.py
  sample-apps/segmentation_spleen_tta/lib/transforms.py
  sample-apps/segmentation_spleen_tta/main.py
  sample-apps/segmentation_spleen_tta/requirements.txt
  sample-apps/segmentation_spleen_tta/validate_TTA.py
Labels: 0.2.0

#323 Interaction enhancements
  .gitignore
  monailabel/deepedit/handlers.py
  monailabel/deepedit/interaction.py
  monailabel/deepedit/transforms.py
  sample-apps/deepedit_spleen/lib/train.py
Labels: 0.2.0

#327 fix compile error - remove tta
  sample-apps/segmentation_spleen/lib/activelearning.py
  sample-apps/segmentation_spleen/main.py
  setup.cfg
Labels: 0.2.0

#333 Update deep edit
  monailabel/utils/others/planner.py
  sample-apps/deepedit/lib/train.py
  sample-apps/deepedit/main.py
  sample-apps/deepedit_left_atrium/README.md
  sample-apps/deepedit_left_atrium/__init__.py
  sample-apps/deepedit_left_atrium/lib/__init__.py
  sample-apps/deepedit_left_atrium/lib/activelearning.py
  sample-apps/deepedit_left_atrium/lib/infer.py
  sample-apps/deepedit_left_atrium/lib/train.py
  sample-apps/deepedit_left_atrium/lib/transforms.py
  sample-apps/deepedit_left_atrium/main.py
  sample-apps/deepedit_left_atrium/model/.gitignore
  sample-apps/deepedit_left_atrium/requirements.txt
  sample-apps/deepedit_spleen/README.md
  sample-apps/deepedit_spleen/__init__.py
  sample-apps/deepedit_spleen/lib/__init__.py
  sample-apps/deepedit_spleen/lib/activelearning.py
  sample-apps/deepedit_spleen/lib/infer.py
  sample-apps/deepedit_spleen/lib/train.py
  sample-apps/deepedit_spleen/lib/transforms.py
  sample-apps/deepedit_spleen/main.py
  sample-apps/deepedit_spleen/model/.gitignore
  sample-apps/deepedit_spleen/requirements.txt
  sample-apps/generic_deepedit/README.md
  sample-apps/generic_deepedit/__init__.py
  sample-apps/generic_deepedit/lib/__init__.py
  sample-apps/generic_deepedit/lib/activelearning.py
  sample-apps/generic_deepedit/lib/infer.py
  sample-apps/generic_deepedit/lib/train.py
  sample-apps/generic_deepedit/lib/transforms.py
  sample-apps/generic_deepedit/main.py
  sample-apps/generic_deepedit/model/.gitignore
  sample-apps/generic_deepedit/requirements.txt
  tests/integration/test_infer.py
  tests/unit/endpoints/context.py
  tests/unit/endpoints/test_batch_infer.py
  tests/unit/endpoints/test_infer.py
  tests/unit/endpoints/test_train.py
Labels: 0.2.0

#334 Add TTA to DeepEdit App
  monailabel/utils/scoring/tta_scoring.py
  sample-apps/deepedit/lib/activelearning.py
  sample-apps/deepedit/main.py
  sample-apps/deepedit/validate_TTA.py
  sample-apps/segmentation_spleen_tta/README.md
  sample-apps/segmentation_spleen_tta/__init__.py
  sample-apps/segmentation_spleen_tta/lib/__init__.py
  sample-apps/segmentation_spleen_tta/lib/activelearning.py
  sample-apps/segmentation_spleen_tta/lib/infer.py
  sample-apps/segmentation_spleen_tta/lib/train.py
  sample-apps/segmentation_spleen_tta/lib/transforms.py
  sample-apps/segmentation_spleen_tta/main.py
  sample-apps/segmentation_spleen_tta/requirements.txt
Labels: 0.2.0

#332 Ohif Plugin fixes
  .github/workflows/pythonapp.yml
  .github/workflows/release.yml
  .github/workflows/weekly-preview.yml
  plugins/ohif/monai-label/src/commandsModule.js
  plugins/ohif/monai-label/src/components/ModelSelector.js
  plugins/ohif/monai-label/src/components/MonaiLabelPanel.js
  plugins/ohif/monai-label/src/components/SegmentationList.js
  plugins/ohif/monai-label/src/components/actions/ActiveLearning.js
  plugins/ohif/monai-label/src/components/actions/AutoSegmentation.js
  plugins/ohif/monai-label/src/components/actions/BaseTab.js
  plugins/ohif/monai-label/src/components/actions/NextSampleForm.js
  plugins/ohif/monai-label/src/components/actions/OptionTable.js
  plugins/ohif/monai-label/src/components/actions/SmartEdit.js
  plugins/ohif/monai-label/src/services/MonaiLabelClient.js
  plugins/ohif/monai-label/src/tools/DeepgrowProbeTool.js
  plugins/ohif/monai-label/src/utils/SegmentationReader.js
  plugins/ohif/monai-label/src/utils/SegmentationUtils.js
Labels: 0.2.0

#338 Merge generic deepgrow/segmentation apps
  monailabel/main.py
  sample-apps/deepgrow/README.md
  sample-apps/deepgrow/__init__.py
  sample-apps/deepgrow/lib/__init__.py
  sample-apps/deepgrow/lib/activelearning.py
  sample-apps/deepgrow/lib/infer.py
  sample-apps/deepgrow/lib/train.py
  sample-apps/deepgrow/lib/transforms.py
  sample-apps/deepgrow/main.py
  sample-apps/deepgrow/model/.gitignore
  sample-apps/deepgrow/requirements.txt
  sample-apps/deepgrow_spleen/README.md
  sample-apps/deepgrow_spleen/__init__.py
  sample-apps/deepgrow_spleen/lib/__init__.py
  sample-apps/deepgrow_spleen/lib/activelearning.py
  sample-apps/deepgrow_spleen/lib/infer.py
  sample-apps/deepgrow_spleen/lib/train.py
  sample-apps/deepgrow_spleen/lib/transforms.py
  sample-apps/deepgrow_spleen/main.py
  sample-apps/deepgrow_spleen/model/.gitignore
  sample-apps/deepgrow_spleen/requirements.txt
  sample-apps/segmentation/README.md
  sample-apps/segmentation/__init__.py
  sample-apps/segmentation/lib/__init__.py
  sample-apps/segmentation/lib/activelearning.py
  sample-apps/segmentation/lib/infer.py
  sample-apps/segmentation/lib/scribbles.py
  sample-apps/segmentation/lib/train.py
  sample-apps/segmentation/lib/transforms.py
  sample-apps/segmentation/main.py
  sample-apps/segmentation/model/.gitignore
  sample-apps/segmentation/requirements.txt
Labels: 0.2.0

#340 Async Tasks + Auto update TTA scores
  monailabel/endpoints/batch_infer.py
  monailabel/endpoints/scoring.py
  monailabel/endpoints/train.py
  monailabel/interfaces/app.py
  monailabel/logging.json
  monailabel/utils/async_tasks/__init__.py
  monailabel/utils/async_tasks/task.py
  monailabel/utils/async_tasks/utils.py
  monailabel/utils/others/app_utils.py
  monailabel/utils/scoring/tta.py
  sample-apps/README.md
  sample-apps/deepedit/main.py
  tests/unit/endpoints/context.py
Labels: 0.2.0

#341 show/hide options tab based on developer mode
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: 0.2.0

#343 Scribbles - Improving execution time for scribbles core transforms
  monailabel/scribbles/transforms.py
  monailabel/scribbles/utils.py
Labels: 0.2.0

#345 Fixing static errors for meta_dict_key
  monailabel/scribbles/transforms.py
Labels: 0.2.0

#346 Scribbles - Remove model-based scribbles methods from generic segmentation app
  monailabel/scribbles/infer.py
  monailabel/scribbles/transforms.py
  sample-apps/deepedit/main.py
  sample-apps/deepgrow/main.py
  sample-apps/deepgrow_left_atrium/main.py
  sample-apps/segmentation/lib/__init__.py
  sample-apps/segmentation/lib/scribbles.py
  sample-apps/segmentation/main.py
  sample-apps/segmentation_left_atrium/main.py
  sample-apps/segmentation_spleen/main.py
  sample-apps/segmentation_spleen_scribbles/lib/__init__.py
  sample-apps/segmentation_spleen_scribbles/lib/scribbles.py
  sample-apps/segmentation_spleen_scribbles/main.py
Labels: 0.2.0

#347 monai 0.7 weekly version + docs theme change
  docs/Makefile
  docs/_static/custom.css
  docs/requirements.txt
  docs/source/apis.rst
  docs/source/conf.py
  docs/source/index.rst
  monailabel/deepedit/transforms.py
  monailabel/interfaces/app.py
  monailabel/interfaces/tasks/infer.py
  monailabel/scribbles/transforms.py
  monailabel/tools/validate_tta.py
  requirements.txt
  sample-apps/segmentation_left_atrium/lib/infer.py
  setup.cfg
Labels: 0.2.0

#351 Sanity check in planner - Add single modality transform
  monailabel/deepedit/transforms.py
  monailabel/utils/others/planner.py
  monailabel/utils/scoring/tta.py
  sample-apps/deepedit/lib/infer.py
  sample-apps/deepedit/lib/train.py
Labels: 0.2.0

#350 Add TTA to all apps
  sample-apps/segmentation/main.py
  sample-apps/segmentation_left_atrium/main.py
  sample-apps/segmentation_spleen/main.py
  sample-apps/segmentation_spleen_scribbles/main.py
Labels: 0.2.0

#336 Removing segmentation_spleen_scribbles app from MONAILabel core
  sample-apps/segmentation_spleen_scribbles/README.md
  sample-apps/segmentation_spleen_scribbles/__init__.py
  sample-apps/segmentation_spleen_scribbles/docs/monailabel_crf.png
  sample-apps/segmentation_spleen_scribbles/docs/monailabel_label_ref_overview.png
  sample-apps/segmentation_spleen_scribbles/docs/scribble_ui.gif
  sample-apps/segmentation_spleen_scribbles/docs/scribble_ui.png
  sample-apps/segmentation_spleen_scribbles/lib/__init__.py
  sample-apps/segmentation_spleen_scribbles/lib/train.py
  sample-apps/segmentation_spleen_scribbles/requirements.txt
Labels: 0.2.0

#354 Scribbles - Improve scribbles ROI to work when no fg scribbles are given
  monailabel/scribbles/transforms.py
Labels: 0.2.0

#353 Improve planner - Add Readme to DeepEdit
  monailabel/utils/others/planner.py
  sample-apps/deepedit/README.md
Labels: 0.2.0

#357 Add spacing & image size args in TTA
  monailabel/tasks/scoring/tta.py
  sample-apps/deepedit/main.py
Labels: 0.2.0

#359 epistemic scoring+strategy
  monailabel/tasks/activelearning/epistemic.py
  monailabel/tasks/scoring/epistemic.py
  sample-apps/segmentation/lib/infer.py
  sample-apps/segmentation/lib/train.py
  sample-apps/segmentation/main.py
  sample-apps/segmentation_left_atrium/main.py
  sample-apps/segmentation_spleen/main.py
Labels: 0.2.0

#360 Delete invalid local dicom seg + handle conversion error for seg
  monailabel/datastore/dicom.py
  monailabel/datastore/utils/convert.py
Labels: 0.2.0

#364 Fix slicer remote download + UI state for selectors
  monailabel/endpoints/datastore.py
  monailabel/utils/others/generic.py
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: 0.2.0

#366 Disable TTA+Epistemic scoring by default for all apps
  sample-apps/deepedit/main.py
  sample-apps/segmentation/main.py
  sample-apps/segmentation_left_atrium/main.py
  sample-apps/segmentation_spleen/main.py
Labels: 0.2.0

#371 Adding unittests for scribbles transforms in ./monailabel/scribbles/transforms.py
  tests/unit/scribbles/__init__.py
  tests/unit/scribbles/test_transforms.py
Labels: 0.2.0

#369 Add Epistemic strategy to DeepEdit App
  monailabel/tasks/scoring/epistemic.py
  monailabel/tasks/scoring/tta.py
  requirements.txt
  sample-apps/README.md
  sample-apps/deepedit/main.py
Labels: 0.2.0

#375 Add figures for scribbles wiki page
  docs/images/scribbles-GeneralScribblesFlow.png
  docs/images/scribbles-on-the-fly-scribbles.png
  docs/images/scribbles-scribbles-based-label-refine.png
  docs/images/scribbles-scribbles-only-mode.png
Labels: 0.2.0

#377 Add images for wiki
  docs/images/classes_monailabel.png
  docs/images/invert_transforms.png
  docs/images/tta.png
Labels: 0.2.0

#376 Add unit tests DeepEdit transforms
  tests/unit/deepedit/test_transforms.py
Labels: 0.2.0

#380 Update docs
  docs/source/appdeployment.rst
  docs/source/installation.rst
  docs/source/quickstart.rst
Labels: 0.2.0

#381 Add unit test for TTA
  sample-apps/deepedit/README.md
  tests/unit/activelearning/__init__.py
  tests/unit/activelearning/test_tta.py
Labels: 0.2.0

#382 Update readme - deepedit
  sample-apps/deepedit/README.md
Labels: 0.2.0

#387 CI/CD: Add Azure CI Pipelines
  .azure/azure-build-test-pipeline.yml
  .azure/azure-release-pipeline.yml
Labels: 0.2.0

#385 Added Dropout Epistemic Uncertainty figure for Wiki
  docs/images/dropout_active_learning.png
Labels: 0.2.0

#384 Add unit test for deepedit interaction
  tests/unit/deepedit/test_interaction.py
Labels: 0.2.0

#394 Unit test to AddRandomGuidance
  tests/unit/deepedit/test_transforms.py
Labels: 0.2.0

#397 Add Python 3.6 to Azure Build-test pipeline
  .azure/azure-build-test-pipeline.yml
Labels: 0.2.0

#401 Update readme
  README.md
Labels: 0.2.0

#408 Weekly Build Fix
  .github/workflows/weekly-preview.yml
  setup.cfg
  setup.py
Labels: bug

#411 Release Dirty Tag Fix
  .github/workflows/release.yml
  requirements.txt
  setup.py
Labels: bug, 0.2.0

#412 Doc updates for custom scoring methods and strategies
  docs/source/modules.rst
Labels: 0.2.0

#418 Updating modules diagram to include scoring methods
  docs/images/modules.svg
Labels: documentation

#420 Update to official MONAI release 0.7.0
  requirements.txt
  setup.cfg
Labels: dependencies

#419 Fix static path endpoints
  monailabel/main.py
Labels: 0.2.0

#421 Missing OHIF static folder content in Wheel File
  MANIFEST.in
Labels: bug

#425 adding whatsnew section to docs for 0.2.0
  docs/source/index.rst
  docs/source/whatsnew.rst
Labels: documentation

#426 slicer roi fix for scribbles
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: slicer client

#429 Image link fixes
  .github/workflows/release.yml
  README.md
Labels: documentation
