Repository Project-MONAI/MONAILabel, pull requests merged in 2021-08, with the labels that each got.

#264 Fix error loading client.py in 3D Slicer plugin
  plugins/slicer/MONAILabel/CMakeLists.txt
  plugins/slicer/MONAILabel/MONAILabel.py
  plugins/slicer/MONAILabel/MONAILabelLib/__init__.py
  plugins/slicer/MONAILabel/MONAILabelLib/client.py
Labels: bug, 0.2.0

#249 Support Scribbles in monailabel
  monailabel/interfaces/tasks/infer.py
  plugins/slicer/MONAILabel/MONAILabel.py
  plugins/slicer/MONAILabel/Resources/Icons/bg_red.svg
  plugins/slicer/MONAILabel/Resources/Icons/eraser.svg
  plugins/slicer/MONAILabel/Resources/Icons/fg_green.svg
  plugins/slicer/MONAILabel/Resources/Icons/gray.svg
  plugins/slicer/MONAILabel/Resources/Icons/tool-brush.svg
  plugins/slicer/MONAILabel/Resources/UI/MONAILabel.ui
  sample-apps/segmentation_spleen_postproc/README.md
  sample-apps/segmentation_spleen_postproc/docs/monailabel_crf.png
  sample-apps/segmentation_spleen_postproc/docs/scribble_ui.gif
  sample-apps/segmentation_spleen_postproc/docs/scribble_ui.png
  sample-apps/segmentation_spleen_postproc/info.yaml
  sample-apps/segmentation_spleen_postproc/lib/__init__.py
  sample-apps/segmentation_spleen_postproc/lib/activelearning.py
  sample-apps/segmentation_spleen_postproc/lib/infer.py
  sample-apps/segmentation_spleen_postproc/lib/scribbles.py
  sample-apps/segmentation_spleen_postproc/lib/train.py
  sample-apps/segmentation_spleen_postproc/lib/transforms.py
  sample-apps/segmentation_spleen_postproc/lib/utils.py
  sample-apps/segmentation_spleen_postproc/main.py
  sample-apps/segmentation_spleen_postproc/model/.gitignore
  sample-apps/segmentation_spleen_postproc/requirements.txt
  sample-apps/segmentation_spleen_postproc/test.py
Labels: 0.2.0

#267 use nibabel vs itk based on constructor config in writer
  monailabel/utils/others/writer.py
Labels: 0.2.0

#268 cleanup generic util class and fix slicer
  monailabel/endpoints/activelearning.py
  monailabel/endpoints/datastore.py
  monailabel/endpoints/download.py
  monailabel/endpoints/infer.py
  monailabel/endpoints/info.py
  monailabel/endpoints/utils.py
  monailabel/main.py
  monailabel/utils/others/app_utils.py
  monailabel/utils/others/generic.py
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: 0.2.0

#270 Slicer Plugin - fix readme and ui label text for accuracy
  README.md
  docs/source/installation.rst
  plugins/slicer/MONAILabel/Resources/UI/MONAILabel.ui
Labels: 0.2.0

#275 Disable train button when no labels are available
  monailabel/scripts/run_monailabel_app.bat
  monailabel/scripts/run_monailabel_app.sh
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: 0.2.0

#283 added CustomAddGuidanced transform with fn_fp_click_ratio arg
  sample-apps/deepedit_spleen/lib/transforms.py
Labels: PR_DO_NOT_MERGE, WORK_IN_PROGRESS

#284 Add TTA as Active Learning
  monailabel/utils/scoring/tta_scoring.py
  sample-apps/segmentation_spleen/lib/activelearning.py
  sample-apps/segmentation_spleen/main.py
Labels: 0.2.0

#296 Change deep edit transforms
  monailabel/deepedit/transforms.py
  sample-apps/deepedit_left_atrium/lib/infer.py
  sample-apps/deepedit_left_atrium/lib/train.py
  sample-apps/deepedit_spleen/lib/infer.py
  sample-apps/deepedit_spleen/lib/train.py
  sample-apps/generic_deepedit/lib/infer.py
  sample-apps/generic_deepedit/lib/train.py
  tests/unit/deepedit/test_transforms.py
Labels: 0.2.0

#295 Fix LGTM issues + enable pytype check for CI Build
  .github/workflows/pythonapp.yml
  monailabel/interfaces/app.py
  monailabel/utils/datastore/dicom/cache.py
  plugins/slicer/MONAILabel/MONAILabel.py
  pyproject.toml
  sample-apps/deepedit_left_atrium/__init__.py
  sample-apps/deepedit_spleen/__init__.py
  sample-apps/deepedit_spleen/lib/train.py
  sample-apps/deepgrow_left_atrium/__init__.py
  sample-apps/deepgrow_spleen/__init__.py
  sample-apps/generic_deepedit/__init__.py
  sample-apps/generic_deepgrow/__init__.py
  sample-apps/generic_segmentation/__init__.py
  sample-apps/segmentation_left_atrium/__init__.py
  sample-apps/segmentation_spleen/__init__.py
  sample-apps/segmentation_spleen_scribbles/__init__.py
  setup.cfg
Labels: 0.2.0

#299 remove any spaces at the beginning and at the end of the uri
  plugins/slicer/MONAILabel/MONAILabelLib/client.py
Labels: 0.2.0

#309 Fix for windows + file lock issues
  monailabel/interfaces/app.py
  monailabel/logging.json
  monailabel/utils/datastore/dicom/cache.py
  monailabel/utils/datastore/dicom/convert.py
  monailabel/utils/datastore/local.py
  runtests.bat
Labels: 0.2.0

#310 DICOMSEG Conversion and Training Issues
  monailabel/interfaces/app.py
  monailabel/main.py
  monailabel/utils/datastore/dicom/cache.py
  monailabel/utils/datastore/dicom/convert.py
  monailabel/utils/datastore/local.py
Labels: 0.2.0
