Repository Project-MONAI/MONAILabel, pull requests merged in 2022-06, with the labels that each got.

#819 add log + scripts to run perf tests for dsa
  .pre-commit-config.yaml
  monailabel/utils/others/pathology.py
  plugins/dsa/cli/MONAILabelAnnotation/MONAILabelAnnotation.py
  tests/dsa/clean.py
  tests/dsa/jobs.py
  tests/dsa/summary.py
Labels: 0.4.0

#820 Support preload flag for radiology + gpu transform for segmentation models
  requirements.txt
  sample-apps/radiology/README.md
  sample-apps/radiology/lib/configs/deepedit.py
  sample-apps/radiology/lib/configs/deepgrow_2d.py
  sample-apps/radiology/lib/configs/deepgrow_3d.py
  sample-apps/radiology/lib/configs/segmentation.py
  sample-apps/radiology/lib/configs/segmentation_spleen.py
  sample-apps/radiology/lib/infers/deepedit.py
  sample-apps/radiology/lib/infers/deepgrow.py
  sample-apps/radiology/lib/infers/segmentation.py
  sample-apps/radiology/lib/infers/segmentation_spleen.py
Labels: 0.4.0

#817 Changed updateSegmentationMask to handle empty segments
  plugins/slicer/MONAILabel/MONAILabel.py
Labels: 0.4.0

#810 NuClick Training & Inference Pipeline Updates
  sample-apps/pathology/lib/infers/nuclick.py
  sample-apps/pathology/lib/trainers/nuclick.py
Labels: 0.4.0

#831 Fix docs for 0.4 version
  README.md
  docs/source/installation.rst
  plugins/dsa/README.md
Labels: 0.4.0

#834 Fix command help for monailabel
  .azure/azure-build-test-gpu-pipeline.yml
  .github/workflows/pythonapp.yml
  .github/workflows/release.yml
  .github/workflows/weekly-preview.yml
  README.md
  monailabel/main.py
  plugins/ohif/README.md
  runtests.sh
  setup.py
  tests/unit/test_main.py
Labels: 0.4.0

#838 Downgrade opencv to 4.5.5.64 to resolve conda env conflicts
  requirements.txt
  setup.cfg
Labels: bug

#839 Docker tests
  .azure/azure-build-test-gpu-pipeline.yml
  .github/workflows/docker.yml
  Dockerfile
Labels: CICD

#845 Fix docs related to 0.4.0
  docs/source/whatsnew.rst
Labels: documentation

#847 Add basic auth with roles [admin, reviewer, annotator, user]
  monailabel/app.py
  monailabel/config.py
  monailabel/endpoints/activelearning.py
  monailabel/endpoints/batch_infer.py
  monailabel/endpoints/datastore.py
  monailabel/endpoints/infer.py
  monailabel/endpoints/info.py
  monailabel/endpoints/login.py
  monailabel/endpoints/logs.py
  monailabel/endpoints/ohif.py
  monailabel/endpoints/proxy.py
  monailabel/endpoints/scoring.py
  monailabel/endpoints/session.py
  monailabel/endpoints/train.py
  monailabel/endpoints/user/__init__.py
  monailabel/endpoints/user/auth.py
  monailabel/endpoints/user/users.json
  monailabel/endpoints/wsi_infer.py
  requirements.txt
  setup.cfg
Labels: 0.5.0
